apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod    #name of the pod
  label:
    name: voting-app-pod    #name of the pod
    app: voting-app     #name of the app itself

spec:
  containers:
    - name: voting-app-pod    #name of the container
      image: kodekloud/examplevotingapp_vote:v1
      ports:
        - containerPort: 80     #pod will listen at port 80