apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  labels:
    name: voting-app-service
    app: voting-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
  selector:
    #copy the metadata lebels from the pods definition file
    name: voting-app-pod    #name of the pod
    app: voting-app     #name of the app itself